### ISSUE TITLE
style attribute in LiveDashboardPlugin conflicts with CSP

### ISSUE THREAD

**Issue by Hermanverschooten** [ezsuite/community#4]
Hi,

In `Phx2Ban.LiveDahboardPlugin` you use the `style` attribute.
If you have a `Content-Security-Policy` set on your site these get blocked.

**Comment by PJUllrich** [comment]
@Hermanverschooten I have a PR ready and will wait for Alex to review it. Basically, you'll need to assign the CSP nonces to your Conn in a Plug before calling the `live_dashboard` route and provide the [csp_nonce_assign_key](https://hexdocs.pm/phoenix_live_dashboard/Phoenix.LiveDashboard.Router.html#live_dashboard/2-options) option. We'll then add the style and img nonces to the LiveDashboard template for you.

I don't have CSP set up so I can't test it myself, but I followed the instructions [in this blog post](https://francis.chabouis.fr/posts/csp-nonce-with-phoenix/#phoenix-livedashboard) and the [LiveDashboard.PageBuilder](https://hexdocs.pm/phoenix_live_dashboard/Phoenix.LiveDashboard.PageBuilder.html#module-custom-hooks) docs. Hopefully, that will do the trick!

**Comment by Hermanverschooten** [comment]
@PJUllrich yes, I have it setup like that, that’s how I noticed.

**Comment by PJUllrich** [comment]
@Hermanverschooten I just released our fixes as `0.2.2`. Could you pull that version and try to

1. pass the Plug.Conn to `Phx2Ban.manually_block_ip_address/1`
2. add the `csp_nonce_assign_key` and try the LiveDashboard plugin again, please?

**Comment by Hermanverschooten** [comment]
1. Done, and ok
2. Perfect!
3. Thanks for the speedy solution
